language: java
jdk:
  - openjdk8

branches: #어떤 브랜치
  only:
    - init

services:
  - mysql

  # Travis CI 서버
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build" # 3.

#gradlew 에러 해결
before_install:
  - chmod +x gradlew
  - sudo mysql -e "use mysql; update user set password=PASSWORD('1234') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gitppo;'


# CI 실행 완료 시 메일 알람
notifications: # 4.
  email:
    recipients:
      - nmj5012@naver.com