language: java
jdk:
  - openjdk8

branches: #어떤 브랜치
  only:
    - init

services:
  - mysql

  # Travis CI 서버
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build" # 3.

#gradlew 에러 해결
before_install:
  - chmod +x gradlew
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS gitppo;'


# CI 실행 완료 시 메일 알람
notifications: # 4.
  email:
    recipients:
      - nmj5012@naver.com
      - hyunahshim@naver.com

# 매번 travis ci에서 파일을 하나하나 복사하는 것은 오래걸리기 때문에 프로젝트 폴더 채로 압축해서 s3로 전달하도록 설정 추가
before_deploy:
  - zip -r gitppo * # 현재 위치의 모든 파일을 gitppo.zip이름으로 압축
  - mkdir -p deploy # deploy라는 디렉토리를 travis ci가 실행중인 위치에 생성
  - mv gitppo.zip deploy/gitppo.zip # gitppo.zip파일을 deploy/로 이동

# travis가 빌드한 결과를 codedeploy가 가져갈 수 있도록 s3에 저장
deploy:
  - provider: s3
    local_dir: deploy # before_deploy에서 생성한 디렉토리 -> 해당 디렉토리 내용들만 s3로 전송
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: gitppo-deploy # S3 버킷 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: Gitppo/Backend #Github 주소
      branch: develop