spring:
  profiles:
    active: local # 기본 환경 선택


# local 환경
---
spring:
  profiles: local

  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    schema: classpath*:db/hsqldb/schema.sql
#    data: classpath*:db/hsqldb/data.sql
    url: jdbc:mysql://gitppo-database.cfmjuvne69nb.ap-northeast-2.rds.amazonaws.com:3306/gitppo
    username: admin
    password: gitppo123!

  jpa:
    database: mysql
    show_spl: true
    hibernate:
      ddl-auto: update # 변경 사항 체크해서 업데이트
      properties:
        hibernate:
          format_sql: true # 압축된 쿼리를 읽기 좋게 포맷

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

logging:
  level:
    org:
      hibernate:
        SQL: debug # 로그 형식으로 쿼리 보여주기